// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: tiles.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tiles [][]byte `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"`
}

func (x *Tiles) Reset() {
	*x = Tiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tiles) ProtoMessage() {}

func (x *Tiles) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tiles.ProtoReflect.Descriptor instead.
func (*Tiles) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0}
}

func (x *Tiles) GetTiles() [][]byte {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type Metatile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopLeft     uint32 `protobuf:"varint,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	TopRight    uint32 `protobuf:"varint,2,opt,name=top_right,json=topRight,proto3" json:"top_right,omitempty"`
	BottomLeft  uint32 `protobuf:"varint,3,opt,name=bottom_left,json=bottomLeft,proto3" json:"bottom_left,omitempty"`
	BottomRight uint32 `protobuf:"varint,4,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
}

func (x *Metatile) Reset() {
	*x = Metatile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metatile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metatile) ProtoMessage() {}

func (x *Metatile) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metatile.ProtoReflect.Descriptor instead.
func (*Metatile) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{1}
}

func (x *Metatile) GetTopLeft() uint32 {
	if x != nil {
		return x.TopLeft
	}
	return 0
}

func (x *Metatile) GetTopRight() uint32 {
	if x != nil {
		return x.TopRight
	}
	return 0
}

func (x *Metatile) GetBottomLeft() uint32 {
	if x != nil {
		return x.BottomLeft
	}
	return 0
}

func (x *Metatile) GetBottomRight() uint32 {
	if x != nil {
		return x.BottomRight
	}
	return 0
}

type Tileset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TileData  map[uint32][]byte `protobuf:"bytes,1,rep,name=tile_data,json=tileData,proto3" json:"tile_data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metatiles []*Metatile       `protobuf:"bytes,2,rep,name=metatiles,proto3" json:"metatiles,omitempty"`
}

func (x *Tileset) Reset() {
	*x = Tileset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tileset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tileset) ProtoMessage() {}

func (x *Tileset) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tileset.ProtoReflect.Descriptor instead.
func (*Tileset) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{2}
}

func (x *Tileset) GetTileData() map[uint32][]byte {
	if x != nil {
		return x.TileData
	}
	return nil
}

func (x *Tileset) GetMetatiles() []*Metatile {
	if x != nil {
		return x.Metatiles
	}
	return nil
}

var File_tiles_proto protoreflect.FileDescriptor

var file_tiles_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x69,
	0x6c, 0x65, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x74, 0x69, 0x6c, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x6f, 0x70, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x74, 0x6f, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x74, 0x74,
	0x6f, 0x6d, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62,
	0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6f, 0x74,
	0x74, 0x6f, 0x6d, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x69, 0x67, 0x68, 0x74, 0x22, 0xb0, 0x01, 0x0a,
	0x07, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x74, 0x69, 0x6c, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x2e, 0x54, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x74, 0x69, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x74, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x74, 0x69, 0x6c, 0x65, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x74, 0x69, 0x6c,
	0x65, 0x73, 0x1a, 0x3b, 0x0a, 0x0d, 0x54, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x6e,
	0x6c, 0x79, 0x6d, 0x69, 0x69, 0x6e, 0x64, 0x2f, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x74, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tiles_proto_rawDescOnce sync.Once
	file_tiles_proto_rawDescData = file_tiles_proto_rawDesc
)

func file_tiles_proto_rawDescGZIP() []byte {
	file_tiles_proto_rawDescOnce.Do(func() {
		file_tiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_tiles_proto_rawDescData)
	})
	return file_tiles_proto_rawDescData
}

var file_tiles_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tiles_proto_goTypes = []interface{}{
	(*Tiles)(nil),    // 0: proto.Tiles
	(*Metatile)(nil), // 1: proto.Metatile
	(*Tileset)(nil),  // 2: proto.Tileset
	nil,              // 3: proto.Tileset.TileDataEntry
}
var file_tiles_proto_depIdxs = []int32{
	3, // 0: proto.Tileset.tile_data:type_name -> proto.Tileset.TileDataEntry
	1, // 1: proto.Tileset.metatiles:type_name -> proto.Metatile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tiles_proto_init() }
func file_tiles_proto_init() {
	if File_tiles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metatile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tileset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tiles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiles_proto_goTypes,
		DependencyIndexes: file_tiles_proto_depIdxs,
		MessageInfos:      file_tiles_proto_msgTypes,
	}.Build()
	File_tiles_proto = out.File
	file_tiles_proto_rawDesc = nil
	file_tiles_proto_goTypes = nil
	file_tiles_proto_depIdxs = nil
}
